name: CI zzdds

on:
  pull_request:
    paths:
      - 'srcZig/**'
  push:
    paths:
      - 'srcZig/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build shape_main
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout dds-rtps
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.16.0"

      - name: Build shape_main
        working-directory: srcZig/zzdds
        run: |
          ZZDDS_VERSION=$( grep "zzdds-" build.zig.zon | cut -d '-' -f 2 )
          echo "ZZDDS_VERSION=${ZZDDS_VERSION}" >> $GITHUB_ENV
          zig build -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseSafe
          cp ./zig-out/bin/zzdds_shape_main_linux zzdds-${ZZDDS_VERSION}-shape_main_linux

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: zzdds-${{ env.ZZDDS_VERSION }}-shape_main_linux
          path: srcZig/zzdds/zzdds-${{ env.ZZDDS_VERSION }}-shape_main_linux
